import image1 from "../assets/images/best-gift.jpg";
import image2 from "../assets/images/kitchen-cup.jpg";
import image3 from "../assets/images/book-author.jpg";
import image4 from "../assets/images/coffee-cup.jpg";

const data = [
  {
    id: 0,
    img: image1,
    title: "Փոքրիկ Նվերի Տուփ",
    originalPrice: 300,
    salePrice: null,
    rating: 5,
    new: false,
    sale: false,
    exist: true,
    bestSeller: false,
  },
  {
    id: 1,
    img: image2,
    title: "Թեյի Բաժակ",
    originalPrice: 4000,
    salePrice: null,
    rating: 3,
    new: true,
    sale: false,
    exist: true,
    bestSeller: true,
  },
  {
    id: 2,
    img: image3,
    title: "Օծանելիք - Դիոր",
    originalPrice: 10000,
    salePrice: 9000,
    rating: 5,
    new: false,
    sale: true,
    exist: true,
    bestSeller: false,
  },
  {
    id: 3,
    img: image4,
    title: "Օծանելիք - Դիոր",
    originalPrice: 6000,
    salePrice: null,
    rating: 4,
    new: false,
    sale: false,
    exist: true,
    bestSeller: true,
  },
  {
    id: 4,
    img: image1,
    title: "Փոքրիկ Նվերի Տուփ",
    originalPrice: 300,
    salePrice: null,
    rating: 5,
    new: true,
    sale: false,
    exist: true,
    bestSeller: false,
  },
  {
    id: 5,
    img: image2,
    title: "Թեյի Բաժակ",
    originalPrice: 4000,
    salePrice: null,
    rating: 5,
    new: true,
    sale: false,
    exist: true,
    bestSeller: false,
  },
  {
    id: 6,
    img: image3,
    title: "Օծանելիք - Դիոր",
    originalPrice: 10000,
    salePrice: 9000,
    rating: 5,
    new: true,
    sale: true,
    exist: true,
    bestSeller: false,
  },
  {
    id: 7,
    img: image4,
    title: "Օծանելիք - Դիոր",
    originalPrice: 6000,
    salePrice: null,
    rating: 5,
    new: true,
    sale: false,
    exist: true,
    bestSeller: false,
  },
  {
    id: 8,
    img: image1,
    title: "Թեյի Բաժակ",
    originalPrice: 4000,
    salePrice: null,
    rating: 5,
    new: true,
    sale: false,
    exist: false,
    bestSeller: false,
  },
  {
    id: 9,
    img: image2,
    title: "Փոքրիկ Նվերի Տուփ",
    originalPrice: 300,
    salePrice: null,
    rating: 5,
    new: true,
    sale: false,
    exist: false,
    bestSeller: false,
  },
  {
    id: 10,
    img: image3,
    title: "Թեյի Բաժակ",
    originalPrice: 4000,
    salePrice: null,
    rating: 5,
    new: true,
    sale: false,
    exist: true,
    bestSeller: false,
  },
  {
    id: 11,
    img: image4,
    title: "Օծանելիք - Դիոր",
    originalPrice: 10000,
    salePrice: 9000,
    rating: 5,
    new: true,
    sale: true,
    exist: true,
    bestSeller: true,
  },
  {
    id: 12,
    img: image1,
    title: "Օծանելիք - Դիոր",
    originalPrice: 6000,
    salePrice: null,
    rating: 5,
    new: true,
    sale: false,
    exist: true,
    bestSeller: false,
  },
  {
    id: 13,
    img: image2,
    title: "Թեյի Բաժակ",
    originalPrice: 4000,
    salePrice: null,
    rating: 5,
    new: true,
    sale: false,
    exist: false,
    bestSeller: true,
  },
  {
    id: 14,
    img: image3,
    title: "Օծանելիք - Դիոր",
    originalPrice: 6000,
    salePrice: null,
    rating: 5,
    new: true,
    sale: false,
    exist: true,
    bestSeller: true,
  },
  {
    id: 15,
    img: image4,
    title: "Թեյի Բաժակ",
    originalPrice: 4000,
    salePrice: null,
    rating: 5,
    new: false,
    sale: false,
    exist: false,
    bestSeller: false,
  },
];

export default data;
